
PROGRAMS                    = client client_www client6 client6_www \
                              server server_www server6 server6_www

CC                          = gcc
GLOBAL_CFLAGS               = -O0 -pipe -Wall -ggdb \
                              -Wmissing-prototypes -Wno-uninitialized -Wstrict-prototypes
GLOBAL_LDFLAGS              = 

### KT2 ################################################################

client_SOURCE               = client.c
client_www_SOURCE           = client_www.c
client6_SOURCE              = client6.c
client6_www_SOURCE          = client6_www.c

server_SOURCE               = server.c
server_www_SOURCE           = server_www.c
server6_SOURCE              = server6.c
server6_www_SOURCE          = server6_www.c

include Makefile.inc

